name: planet-hack
channels:
  - conda-forge
dependencies:
  - python=3.8 
  - geopandas
  - jupyter
  - matplotlib
  - numpy
  - pandas<1.1
  - rasterio
  - requests
  - scikit-learn
  - xarray
  - pip
  - pip:
    - planet
